import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Nav from "@/components/Nav";
import Results from "../components/Results";
import requests from "../../utils/requests";
import { useEffect, useState } from "react";

const inter = Inter({ subsets: ["latin"] });

export default function Home({ results }) {
  const [allData, setAllData] = useState();
  useEffect(() => {
    const fetchData = async () => {
      try {
        const request = await fetch(
          `https://api.themoviedb.org/3/trending/all/week?api_key=6e07dbaff15749ef8b6ce1d13d86f176&language=en-US`
        ).then((res) => {
          return res.json();
        });

        setAllData(request?.results);
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    };

    fetchData();
  }, []);

  return (
    <>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Nav */}
      <Nav />

      {/* Results */}
      {allData?.length > 0 && <Results results={allData} />}
    </>
  );
}

export async function getServerProps(context) {
  const genre = context.query.genre;

  /* const request = await fetch(
    `https://api.themoviedb.org/3${
      requests[genre]?.url || requests.fetchTrending.url
    }`
  ).then((res) => {
    console.log(res.json(), "INSIDE SERVER");
    return res.json();
  }); */
  const request = await fetch(
    `https://api.themoviedb.org/3/trending/all/week?api_key=6e07dbaff15749ef8b6ce1d13d86f176&language=en-US`
  ).then((res) => {
    return res.json();
  });

  return {
    props: {
      results: request.results,
    },
  };
}
