import Head from "next/head";
import { Inter } from "next/font/google";
import Header from "@/components/Header";
import Nav from "@/components/Nav";
import Results from "../components/Results";
import { useEffect, useState } from "react";
import requests from "../../utils/requests";

export default function Home(props) {
  const [allData, setAllData] = useState();

  useEffect(() => {
    const fetchData = async () => {
      try {
        const genre = props?.query?.genre || "fetchTrending";
        const request = await fetch(
          `https://api.themoviedb.org/3${requests[genre]?.url}`
        ).then((res) => {
          return res.json();
        });

        setAllData(request?.results);
      } catch (error) {
        console.error("Error fetching data:", error);
      }
    };

    fetchData();
  }, [props?.query?.genre]);

  return (
    <>
      <Head>
        <title>Hulu 2.0</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* Header */}
      <Header />

      {/* Nav */}
      <Nav />

      {/* Results */}
      {allData?.length > 0 && <Results results={allData} />}
    </>
  );
}

export async function getServerSideProps(context) {
  // Get the query parameters from the context
  const { query } = context;

  // Get the path from the request URL in the context
  const path = context.req.url;

  // Make API request based on the query parameters (if needed)
  const request = await fetch(
    `https://api.themoviedb.org/3/trending/all/week?api_key=YOUR_API_KEY&language=en-US`
  ).then((res) => {
    return res.json();
  });

  return {
    props: {
      results: request,
      query, // Pass the query parameters as a prop
      path, // Pass the path as a prop
    },
  };
}
